apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: baselab
  annotations:
    kubernetes.io/ingress.class: "nginx"    

spec:
  tls:
  - hosts:
    - keycloak.{{ lab_domain }}
  rules:
  - host: keycloak.{{ lab_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 80