---
- hosts: localhost
  connection: local
  #gather_facts: yes
  #become: yes
  roles:
    - role: storage
    - role: deployments/namespace
    - role: deployments/nginx-rgb
    - role: deployments/juiceshop
    - role: deployments/echoserver
    - role: deployments/pihole
    - role: deployments/keycloak