---
# deploy applications
- hosts: localhost
  connection: local
  gather_facts: false

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: metallb 
      when: metallb_deploy == true

  roles:
    - role: storage
    - role: deployments/namespace
    - role: deployments/nginx-rgb
    - role: deployments/juiceshop
    - role: deployments/echoserver
    - role: deployments/pihole
    - role: deployments/keycloak

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: deploy NGINX Ingress 
      block:
        - name: NGINX Ingress Controller
          include_role: 
            name: ingress/nginx
        - name: Keycloak Ingress
          include_role: 
            name: app-ingress/keycloak
        - name: NGINX RGB Ingress
          include_role: 
            name: app-ingress/nginx-rgb
        - name: Echo Ingress
          include_role: 
            name: app-ingress/echoserver
        - name: NGINX Juice Shop Ingress
          include_role: 
            name: app-ingress/juiceshop
        - name: NGINX PiHole Ingress
          include_role: 
            name: app-ingress/pihole
      when: ingress_deploy == "nginx"

    - name: deploy clusterip services
      block:
        - name: NGINX RGB clusterip
          include_role: 
            name: services/clusterip/nginx-rgb
        - name: Juice Shop clusterip
          include_role: 
            name: services/clusterip/juiceshop
        - name: Echo Server clusterip
          include_role: 
            name: services/clusterip/echoserver
        - name: PiHole clusterip
          include_role: 
            name: services/clusterip/pihole
        - name: Keycloak clusterip
          include_role: 
            name: services/clusterip/keycloak   
      when: service_type == "clusterip"

    - name: deploy loadbalancer services
      block:
        - name: NGINX RGB lb
          include_role: 
            name: services/loadbalancer/nginx-rgb
        - name: Juice Shop lb
          include_role: 
            name: services/loadbalancer/juiceshop
        - name: Echo Server lb
          include_role: 
            name: services/loadbalancer/echoserver
        - name: PiHole lb
          include_role: 
            name: services/loadbalancer/pihole
        - name: Keycloak lb
          include_role: 
            name: services/loadbalancer/keycloak   
      when: service_type == "loadbalancer"
