---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: baselab
spec:
  selector:
    app: echoserver
  ports:
    - nodePort: 31080
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
