---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: baselab
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    nodePort: 31180
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31443
    port: 443
    protocol: TCP
    targetPort: 8443
  type: NodePort
   