---
kind: Service
apiVersion: v1
metadata:
  name: pihole-udp
  namespace: baselab
spec:
  selector:
    app: pihole-sts
    statefulset.kubernetes.io/pod-name: pihole-sts-0
  ports:
  - protocol: UDP
    port: 53
    name: dnsudp
    targetPort: 53
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-tcp
  namespace: baselab
spec:
  selector:
    app: pihole-sts
    statefulset.kubernetes.io/pod-name: pihole-sts-0
  ports:
  - protocol: TCP
    nodePort: 31553
    port: 53
    name: dnstcp
    targetPort: 53
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-http
  namespace: baselab
spec:
  selector:
    app: pihole-sts
    statefulset.kubernetes.io/pod-name: pihole-sts-0
  ports:
  - protocol: TCP
    nodePort: 31580
    port: 80
    name: http
    targetPort: 80
  - protocol: TCP
    nodePort: 31943
    port: 443
    name: https
    targetPort: 443
  type: NodePort