---
- name: Remove NGINX Ingress
  k8s:
    state: absent      
    src: "{{ playbook_dir }}/k8s_yamls/nginx-ingress.yml"

- name: Remove ingress-nginx namespace
  k8s:
    name: ingress-nginx 
    api_version: v1
    kind: Namespace
    state: absent 