---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  labels:
    app: juiceshop
  namespace: baselab
spec:
  selector:
    matchLabels:
      app: juiceshop
  replicas: 1
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: bkimminich/juice-shop
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000