---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: baselab
  labels:
    app: keycloak
spec:
  serviceName: keycloak-headless
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:      
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:16.1.1
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/data
            subPath: opt/jboss/keycloak/standalone/data
            name: keycloakdata  
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
  volumeClaimTemplates:
  - metadata:
      name: keycloakdata
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: baselab
  labels:
    app: keycloak
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: keycloak