---
apiVersion: v1
kind: Service
metadata:
  name: pihole-headless
  namespace: baselab
  labels:
    app: pihole-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: pihole-sts

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole-sts
  namespace: baselab
spec:
  selector:
    matchLabels:
      app: pihole-sts
  serviceName: pihole-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: "pihole-sts"
    spec:
      containers:
      - env:
        - name: TZ
          value: "America/New_York"
        - name: WEBPASSWORD
          value: password1234
        - name: DNS1
          value: 9.9.9.9
        - name: DNS2
          value: 8.8.8.8
        name: pihole
        image: "pihole/pihole:latest"
        imagePullPolicy: Always
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dchp
          containerPort: 67
          protocol: UDP
        - name: web
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: pv-data
          mountPath: "/etc/pihole"
          subPath: "etc/pihole"
        - name: pv-data
          mountPath: "/etc/dnsmasq.d"
          subPath: "etc/dnsmasq.d"
        - name: var-log
          mountPath: "/var/log"
          subPath: "var/log"
        - name: var-log-lighttpd
          mountPath: "/var/log/lighttpd"
          subPath: "var/log/lighttpd"
      volumes:
      - name: var-log
        emptyDir:
          medium: Memory
      - name: var-log-lighttpd
        emptyDir:
          medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: pv-data
    spec:
      storageClassName: managed-nfs-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
