---
- name: Remove NGINX RGB deployment
  k8s:
    state: absent            
    namespace: baselab  
    src: "{{ playbook_dir }}/k8s_yamls/deployments/nginx-rgb.yml"

- name: Remove NGINX Red deployment
  k8s:
    state: absent           
    namespace: baselab  
    src: "{{ playbook_dir }}/k8s_yamls/deployments/nginx-red.yml"

- name: Remove NGINX Green deployment
  k8s:
    state: absent           
    namespace: baselab  
    src: "{{ playbook_dir }}/k8s_yamls/deployments/nginx-green.yml"

- name: Remove NGINX Blue deployment
  k8s:
    state: absent           
    namespace: baselab  
    src: "{{ playbook_dir }}/k8s_yamls/deployments/nginx-blue.yml"
