---
- name: Create Keycloak ingress
  k8s:
    state: present           
    definition:
      apiVersion: v1
      kind: Ingress 
      metadata:
        name: keycloak
        namespace: baselab
        annotations:
          kubernetes.io/ingress.class: nginx
      spec:
        tls:
        - hosts:
          - "keycloak.{{ lab_domain }}"
          secretName: pcl-tls-secret
        rules:
        - host: "keycloak.{{ lab_domain }}"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: keycloak
                  port:
                    number: 80            