---
# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "Your/Timezone"

# NFS Client Configuration 
nfs_server: "192.168.1.10"
nfs_path: "/srv/nfs/kubedata"

# Ingress IP
# Set IP from service loadbalancer range
ingress_ip: "192.168.1.90"
