---
# this is the user that has ssh access to these machines
ansible_user: ansibleuser

# NFS Client Configuration 
nfs_server: "192.168.1.10"
nfs_path: "/srv/nfs/kubedata"

# interface which will be used for CNI interface
cni_iface: "ens6"

# metallb install flag
metallb_deploy: true

# image tag for metal lb
metallb_version: "v0.13.9"

# metallb ip range for load balancer
metal_lb_ip_range: "192.168.1.80-192.168.1.90"

# Select ingress 'nginx' or 'none'
ingress_deploy: "nginx"

# Ingress IP
# Set IP from service loadbalancer range
ingress_ip: "192.168.1.90"

# Select the service tpye 'nodeport', 'clusterip' or 'loadbalancer'
service_type: "clusterip"

# Lab domain
lab_domain: "lab.example.com"

# nginx ingress manifest url
nginx_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.7.0/deploy/static/provider/cloud/deploy.yaml"