---
- name: Create OWASP Juice Shop LoadBalancer Service
  k8s:
    state: present            
    namespace: baselab  
    src: "{{ playbook_dir }}/k8s_yamls/services/loadbalancer/juiceshop-svc-lb.yml"
