---
- name: Download NGINX Ingress manifest 
  ansible.builtin.get_url:
    url: "{{ nginx_url }}"
    dest: "{{ playbook_dir }}/k8s_yamls/nginx-ingress.yml"
    mode: 0664

- name: Update NGINX Ingress yaml with loadbalancer IP
  shell: sed -i -e '/type:\ LoadBalancer/a '"\  loadBalancerIP:\ {{ ingress_ip }}" '{{ playbook_dir }}'/k8s_yamls/nginx-ingress.yml

- name: Install NGINX Ingress
  k8s:
    state: present          
    src: "{{ playbook_dir }}/k8s_yamls/nginx-ingress.yml"

- name: "Status of the NGINX Ingress controller"
  k8s_info:
    kubeconfig: "~/.kube/config"
    api_version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
  register: ingress_service
  until: ingress_service.resources | json_query('[*].status.conditions[?reason==`NewReplicaSetAvailable`][].status') | select ('match','True') | list | length == 1
  delay: 15
  retries: 10