---
- name: Create PiHole ingress
  k8s:
    state: present           
    definition:
      apiVersion: v1
      kind: Ingress 
      metadata:
        name: pihole
        namespace: baselab
        annotations:
          kubernetes.io/ingress.class: nginx
      spec:
        tls:
        - hosts:
          - "pihole.{{ lab_domain }}"
        rules:
        - host: "pihole.{{ lab_domain }}"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: pihole-http
                  port:
                    number: 80         