---
apiVersion: v1
kind: Service
metadata:
  name: juiceshop
  namespace: baselab
spec:
  selector:
    app: juiceshop
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: ClusterIP