---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rgb
  namespace: baselab
spec:
  selector:
    app: nginx-rgb
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-green
  namespace: baselab
spec:
  selector:
    app: nginx-green
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-blue
  namespace: baselab
spec:
  selector:
    app: nginx-blue
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-red
  namespace: baselab
spec:
  selector:
    app: nginx-red
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80