---
- name: Create OWASP Juice Shop NodePort Service
  k8s:
    state: present            
    namespace: baselab  
    src: "{{ playbook_dir }}/k8s_yamls/services/nodeport/juiceshop-svc-nodeport.yml"
