- name: Download Cert-Manager manifest 
  ansible.builtin.get_url:
    url: "https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml"
    dest: "{{ playbook_dir }}/k8s_yamls/ca/cert-manager.yml"
    mode: '0664'

- name: Install Cert-Manager
  k8s:
    state: present          
    src: "{{ playbook_dir }}/k8s_yamls/ca/cert-manager.yml"

- name: Generate The PCL CA private key 
  community.crypto.openssl_privatekey:
    path: "{{ playbook_dir }}/k8s_yamls/ca/crt-key/ca.key"
    size: 4096
    type: RSA

- name: Create certificate signing request (CSR) for PCL CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ playbook_dir }}/k8s_yamls/ca/crt-key/ca.key"
    common_name: PCL CA
    use_common_name_for_san: false  
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Generate The PCL CA certificate
  community.crypto.x509_certificate:
    path: "{{ playbook_dir }}/k8s_yamls/ca/crt-key/ca.crt"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ playbook_dir }}/k8s_yamls/ca/crt-key/ca.key"
    provider: selfsigned

- name: Create CA Secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pcl-ca-secret
        namespace: cert-manager
      type: Opaque
      data: 
        tls.crt: "{{ lookup('file', '{{ playbook_dir }}/k8s_yamls/ca/crt-key/ca.crt')|b64encode}}"
        tls.key: "{{ lookup('file', '{{ playbook_dir }}/k8s_yamls/ca/crt-key/ca.key')|b64encode}}"

- name: Create Cluster Issuer
  k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: pcl-clusterissuer
      spec:
        ca:
          secretName: pcl-ca-secret

- name: Create a baselab namespace
  k8s:
    name: baselab 
    api_version: v1
    kind: Namespace
    state: present    

- name: Create PCL SAN Certificate
  k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: pcl-san-cert
        namespace: baselab
      spec:
        secretName: pcl-tls-secret
        issuerRef:
          name: pcl-clusterissuer
          kind: ClusterIssuer
        dnsNames:
          - echo.{{ lab_domain }}
          - juice.{{ lab_domain }}
          - keycloak.{{ lab_domain }}
          - rgb.{{ lab_domain }}
          - red.{{ lab_domain }}
          - green.{{ lab_domain }}
          - blue.{{ lab_domain }}
          - pihole.{{ lab_domain }}

